### PR TITLE
Update go check to currently supported versions

### PR DESCRIPTION
**Pull request by sinato**
Go1.7 is released and Go1.5 is expired.
ref. https://golang.org/dl/#stable

I have read CONTRIBUTING and signed the CNCF CLA, but please let me know if I've missed anything.

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the PR, though I don't expect these to be updated with every go release, only as needed when building new releases of this project (which are expected to be rare going forward)

making the go version check just a warning for the make targets other than `build-release` could make sense to avoid blocking people running local builds/installs

**Comment by sinato** [comment]
Sorry, you're right! I missed the pre-built binary and failed to build, so I created a PR, but it is not necessary.

**Comment by sinato** [comment]
> making the go version check just a warning for the make targets other than build-release could make sense to avoid blocking people running local builds/installs

Is it like this? d2ffbc2 
Anyway, please don't hesitate to close the PR if it's not necessary

**Comment by liggitt** [comment]
I think something like https://github.com/kubernetes-sigs/kubectl-check-ownerreferences/pull/7 would work better, completely relaxing the go version check when people are building locally, and stamping the go version info into the build instead to be able to tell if an issue was potentially related to the go version

**Pull request closed without merging**
